### ISSUE TITLE
Horizontal interpolation of microCAT data near the surface

### ISSUE THREAD

**Issue by LewisDrysdale** [ScotMarPhys/m_moorproc_toolbox#10]
Near surface gridded and merged data are horizontally interpolated to eliminate small temporal gaps due to spike removal or instrument knockdown. In come cases, however, the resulting data are not realistic.  

Figure from Alan
![test(14)](https://user-images.githubusercontent.com/45363219/186147232-6725a6f9-1268-46bf-96c7-60392e1a3783.png)

**Comment by LewisDrysdale** [comment]
I have assigned a few folk but not expecting anyone to do anything quite yet. The code is buried towards the end of the merge scripts,. /exec/gitrrepo/stage3/griddding/MCAT/merge[....].mlx, search for **depthminforinterp**
I'll put some more info on here when I am back from leave in September

**Comment by alanfox** [comment]
I don't know much matlab but there are often parallel functions in python. There doesn't seem to be a facility to give interp1 function a max gap in either, so I think maybe the easiest way to stop interpolation in time across 'long' gaps might be to do the interpolation then replace the interpolated numbers in the long gaps with nan. Not sure how to do this in matlab, but in python it could be something like this:

[I'm also learning how to add/respond to markdown comments in Github, including code and figures, so sorry this is a bit long]

# Masking long gaps in interpolated timeseries
Doesn't do the interpolation, just exploring how to mask gaps after interpolation


```python
import numpy as np
import matplotlib.pyplot as plt
```

#### parameters


```python
max_gap=2
```

### Make an array (x) and a gappy array (y) to test on
These represent the interpolated (no gaps) and original (gaps) arrays respectively


```python
t = np.arange(0,2*np.pi,np.pi/50.0)
x = np.sin(t)
```


Add some random NaNs. Enough to make some sequences of NaN


```python
np.random.seed(0)
mask = np.random.randint(0,3,x.shape[0]).astype(float)
mask=mask/mask # lazy: warning about divide by zero
y=x*mask
```

```python
y
```


    array([        nan,  0.06279052,         nan,  0.18738131,  0.24868989,
            0.30901699,         nan,  0.42577929,         nan,         nan,
                   nan,  0.63742399,  0.68454711,  0.72896863,  0.77051324,
                   nan,  0.84432793,  0.87630668,  0.90482705,  0.92977649,
                   nan,  0.96858316,         nan,         nan,  0.99802673,
            1.        ,         nan,  0.9921147 ,         nan,  0.96858316,
            0.95105652,  0.92977649,         nan,  0.87630668,  0.84432793,
            0.80901699,         nan,  0.72896863,         nan,  0.63742399,
            0.58778525,         nan,  0.48175367,         nan,         nan,
                   nan,  0.24868989,  0.18738131,  0.12533323,         nan,
                   nan, -0.06279052,         nan, -0.18738131, -0.24868989,
           -0.30901699,         nan, -0.42577929, -0.48175367, -0.53582679,
           -0.58778525, -0.63742399, -0.68454711, -0.72896863,         nan,
           -0.80901699, -0.84432793,         nan, -0.90482705, -0.92977649,
                   nan,         nan, -0.98228725,         nan,         nan,
                   nan,         nan,         nan,         nan, -0.96858316,
                   nan, -0.92977649, -0.90482705, -0.87630668, -0.84432793,
                   nan, -0.77051324, -0.72896863, -0.68454711,         nan,
           -0.58778525, -0.53582679,         nan, -0.42577929, -0.36812455,
                   nan, -0.24868989,         nan, -0.12533323, -0.06279052])

```python
plt.scatter(t,x,s=4,marker='o',label='full timeseries')
plt.scatter(t,y-0.1,s=4,marker='o',label='with data gaps (y-offset -0.1)')
plt.legend();
```

![output_9_1](https://user-images.githubusercontent.com/7387943/186440450-9121b5ed-0d62-44a2-8d75-d398cac461d6.png)

### Function to shift values to right or left in numpy array
There may be a built-in function. There is in python xarray.


```python
def shift5(arr, num, fill_value=np.nan): #shifts array, fills end with fill_value, crops other end 
    result = np.empty_like(arr)
    if num > 0:
        result[:num] = fill_value
        result[num:] = arr[:-num]
    elif num < 0:
        result[num:] = fill_value
        result[:num] = arr[-num:]
    else:
        result[:] = arr
    return result
```

### Function to find 'long' datagaps


```python
def find_long_nansequence(a,max_gap): # clumsy way of checking for sequences of Nan longer than max_gap in array y
    # reduces sequences of nans by max_gap elements, so anything shorter is lost
    # returns a boolean array where 'False' means the value is part of a long gap
    m = np.zeros_like(y).astype(bool)
    for i in range(max_gap+1):
        m += ~np.isnan(shift5(a,i,0))
    # adds max_gap elements back on to sequence
    m2 = np.ones_like(y).astype(bool)
    for i in range(max_gap+1):
        m2 *= shift5(m,-i,1)
    return m2

```

### Find the 'long' datagaps (> max_gap)


```python
mask2 = find_long_nansequence(y,max_gap)
mask2
```




    array([ True,  True,  True,  True,  True,  True,  True,  True, False,
           False, False,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True, False, False,
           False,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True, False, False, False, False, False, False,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True,  True,  True,  True,  True,  True,  True,  True,  True,
            True])



### Overwrite x with NaN across these long gaps


```python
z=np.where(mask2==True,x,np.nan)
```

### Plot
Notice how the short gaps in the orange 'line' are filled in the green 'line', but the longer gaps are left.


```python
t=np.arange(0.0,100.0,1.0)
plt.scatter(t,x,s=4,marker='o',label='full timeseries')
plt.scatter(t,y-0.1,s=4,marker='o',label='with data gaps (y-offset -0.1)')
plt.scatter(t,z+0.1,s=4,marker='o',label='keep long gaps (y-offset +0.1)')
plt.legend();

```
![output_18_1](https://user-images.githubusercontent.com/7387943/186440140-a5f28a8f-ae06-41ee-8816-25cf60c051fe.png)

**Comment by Kristin-2002** [comment]
I added a correction in the microcats as well as current meter gridded scripts to set any knockdown event to nan again:

In directory: "m_moorproc_toolbox\exec\gitrepo\stage3\gridding\CM"
file: "stage3_4c_time_interp_data.m"
    % KB, 27/3/2024
    % Added code to remove horizontal interpolation when mooring was knocked down 
    % This was not needed before because data was vertical extrapolated to surface 
    % first which is now done in later step.

    for i = 1:length(JG);
        iu = find(~isnan(RT_merg_CM.UGfs(:,i)),1,'first');
        iv = find(~isnan(RT_merg_CM.VGfs(:,i)),1,'first');
        iw = find(~isnan(RT_merg_CM.WGfs(:,i)),1,'first');

        VG_2(1:iv-1,i)=nan;
        UG_2(1:iu-1,i)=nan;
        WG_2(1:iw-1,i)=nan;
    end

In directory
"m_moorproc_toolbox\exec\gitrepo\stage3\gridding\MCAT"
Files
"merge_osnap_data_east.m"
"merge_osnap_data_west.m"

 % KB, 27/3/2024
    % Added code to remove horizontal interpolation when mooring was knocked down 
    % This was not needed before because data was vertical extrapolated to surface 
    % first which is now done in later step.

for i = 1:length(JG);
    it = find(~isnan(TGfs(:,i)),1,'first');
    is = find(~isnan(SGfs(:,i)),1,'first');
    
    if pgg(it)<=500
    TG_east(1:it-1,i)=nan;
    end
    if pgg(is)<=500
    SG_east(1:is-1,i)=nan;
    end
end
