### ISSUE TITLE
Branch merging strategy

### ISSUE THREAD

**Issue by Kristin-2002** [ScotMarPhys/m_moorproc_toolbox#29]
Hi all,

I would like to use this issue to develop a branch merging strategy and would appreciate you thoughts on it. 

My suggestion is building on what has been already established before:

1. Create a new branch for each cruise.
2. When cruise is finalised the creator of the branch will create a pull request to merge the branch with the master branch.
3. A contributor who is not the creator of the branch will review the pull request and check the changes made. 
4. If the reviewer finds no issues they will continue to 5. If there are issues or even merge conflicts the reviewer will raise issues/discussions which can then be discussed by everyone to finally agree on changes to be made by creator. After the changes are made by creator and any merge conflicts are resolved steps 2-4 will be repeated.
5.  If everything is ok the reviewer can verified the pull request and merge the cruise and master branch.

As a control I would suggest to protect the branches so nobody can merge them without a review.

It might be also of value to only let a limited group give rights to agree the pull requests (maybe at the beginning I would suggest Yvonne, Lewis and me)

Next step:

- [ ] agree on merging strategy
- [x] protect branches
- [x] Lewis or Kristin to create pull request of JC238 to master - following new strategy resolving any merge conflicts as they arise
- [ ] After that, Yvonne to create pull request to master - following new strategy resolving any merge conflicts as they arise
- [ ] Develop training based on updated master branch
- [ ] Create new branch

**Comment by yfiring** [comment]
We may need to define "when a cruise is finalised" -- is this at the end of a cruise? Once the data from that cruise are all processed?

**Comment by Kristin-2002** [comment]
Good point. Probably you will have it never really done. I am wondering whether we combine the merging to the master with milestones such as data submissions.

My idea behind this is, that before we submit the data set and get an doi, we create a pull request and someone second check the code before data publication. I see that this might happened at least twiced at different time points:

1. The calibrated instrument time series submitted do BODC .
2. Much later, the merge product which comes along with the creation of transport products, which is also associated with the publication of a paper.

At both steps we can aim to get a doi for the particular code version at Zenodo, which can then be referenced to the data product. This is then with each data publication updated, Zenodo will have a doi for each version of the code submitted and also a doi for the toolbox in general which will always link to the most recent version.

Here an example of my first code I submitted to Zenodo. Probably not the best practice, but you can get an idea how it would look like with different versions, etc: https://zenodo.org/records/10817327

Would do you think?

**Comment by Kristin-2002** [comment]
Another reason to merge the cruise branch into the master would be before a cruise. E.g. I think it would be desirable to pull the toolbox from DY174 simply because is was set up on discovery and worked. However, there are also some changes in the JC238 toolbox regarding stage 3 (the much later merging step) which would be great to propagate.

So for DY181 I would be tempted to merge JC238 into the master - (which might be still developed for stage 3) and then DY174 (which will further develope for calibration and later merging - i am imagine).

Or we merge JC238 in master and DY174 pull the changes and for DY181 we pull from DY174. (Each time I would a second person let review the pull request to verify the merge....)

**Comment by Kristin-2002** [comment]
@yfiring @sjones1000 @LewisDrysdale @smithhek 

Hi all,

I would like to progress and would suggest to 
1. protect any branches so they cannot be easily merged and 
2. merge JC238 to master to avoid letting the master fall to far behind by end of this week (26.04.).

@yfiring - Would you be able to admit the pull request next week (29.04.-03.05.)? I do not expect any merge conflicts.

Thank you
Kristin

**Comment by yfiring** [comment]
This all makes sense to me and sounds like good practice going forward, except that dois for successive versions of the code seems to duplicate the version control a little (and because the data are processed as we go along, not every step was necessarily done with the latest version, so metadata still need to refer to the range of commits). Also (later) we should discuss how to handle post-cruise parallel processing/development. 
Yes @Kristin-2002 I can admit the pull request on jc238-->master next week, and then set one up for dy174-->master.

**Comment by Kristin-2002** [comment]
I protected the master branch. It requires at least one review before merging is allowed.

I am wondering how to protect the branches for the different cruises. Maybe the main branches DY120, JC238, DY174 should be protected after the cruise with one reviewer necessary before merging. For example for DY174: Any development after cruise can be added as new branch (e.g. DY174_post_cruise_calibration) and when that is final the actor will rise pull request into the DY174 branch which requires at least one review. After that, to keep the master branch up to date, we can create a pull request from DY174 to master.

Could be a release of the cruise branch (e.g. JC238) associated with the data release be an option? Additionally, we could also lock the branch then (cannot be changed or deleted). Again, I can see this happens twice (once calibrated moorings are submitted to BODC and once a merge product is released). We might end up with two branches per cruise then.

**Comment by Kristin-2002** [comment]
@yfiring @LewisDrysdale 

Is there any value in keeping the following branches:

- https://github.com/ScotMarPhys/m_moorproc_toolbox/tree/DY120-add-IBmoors
- https://github.com/ScotMarPhys/m_moorproc_toolbox/tree/JC238-proc-RTmoor-noc

Otherwise I would remove them to keep the repository clean.

**Comment by yfiring** [comment]
JC238-proc-RTmoor-noc: you've merged it, it can go

**Comment by Kristin-2002** [comment]
@yfiring @LewisDrysdale 
I linked a new branch to this issue where I revised the readme and the processing documents to reflect the new merging strategy. it is not a complete revision of the processing doc - but it would be a start. Would be great if you can have a look at it.
